FROM rocker/r-ver:4.0.2

RUN apt-get update -qq && apt-get install -y \
  libssl-dev \
  libcurl4-gnutls-dev
  
RUN apt-get install -y curl

RUN R -e "install.packages(c('neo4r', 'plumber'))"

COPY / /

EXPOSE 4321

ENTRYPOINT ["Rscript", "main.R"]